server:
  image: mkulumadzi/celebrity-server:latest
  links:
    - mongodb:mongodb
  ports:
    - "8080:8080"
  environment:
    MONGO_HOST: mongodb
    WEB_HOST: celebrity.kuyenda.io
mongodb:
  image: mongo
  expose:
    - "27017"
  ports:
    - "27017:27017"
webapp:
  image: mkulumadzi/celebrity-game:latest
  links:
  - server:api1
  ports:
  - "80:80"
